name: teledart
description: A Dart library interfacing with the latest Telegram Bot API.
version: 0.1.6
homepage: https://github.com/DinoLeung/TeleDart
issue_tracker: https://github.com/DinoLeung/TeleDart/issues

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  json_annotation: ^3.1.1
  http: ^0.12.2

dev_dependencies:
  test: ^1.15.7
  build_runner: ^1.10.11
  json_serializable: ^3.5.1
  pedantic: ^1.11.0
