name: teledart
description: A Dart library interfacing with the latest Telegram Bot API.
version: 0.3.4
homepage: https://github.com/DinoLeung/TeleDart
issue_tracker: https://github.com/DinoLeung/TeleDart/issues

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  json_annotation: ^4.4.0
  http: ^0.13.4

dev_dependencies:
  test: ^1.20.1
  build_runner: ^2.1.7
  json_serializable: ^6.1.3
  lints: ^1.0.1
